name: Linting with flake8
on: [ push, pull_request ]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install requirements
        run: pip install flake8
      - name: Run flake8
        run: flake8